# Generated by Django 4.2 on 2023-04-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_departamento_funcionario_empresa_and_more'),
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohoraextra',
            options={'verbose_name': 'Registro de Hora Extra', 'verbose_name_plural': 'Registros de Hora Extra'},
        ),
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario', verbose_name='Funcionário'),
            preserve_default=False,
        ),
    ]
